
server:
  tomcat:
    connection-timeout: 10s
    keep-alive-timeout: 15s
    threads:
      max: 25
      min-spare: 5
spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/find-my-doc-db
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
management:
  endpoints:
    web:
      exposure:
        include: '*'
#      ddl-auto: create