server:
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 100
      min-spare: 10
spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/find-my-doc-db
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create